### PR TITLE
with custom marshaller

### PR DESCRIPTION
**Pull request by makasim**
fixes https://github.com/lestrrat-go/fluent-client/issues/29

### CODE REVIEW

**Comment by lestrrat** [comment]
This is still work in progress, right?

**Comment by makasim** [comment]
nope, that's it

**Comment by lestrrat** [comment]
Ah, I see what you are trying to do.

**Comment by lestrrat** [comment]
I had to do some fixing of the infrastructure to make tests pass, but it has been merged.

**Pull request closed without merging**
